global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "spring-transaction-play-class"
    metrics_path: '/actuator/prometheus'
    scheme: http
    static_configs:
      - targets: ['host.docker.internal:8083']
    basic_auth:
      username: "${PROMETHEUS_BASIC_AUTH_USERNAME}"
      password: "${PROMETHEUS_BASIC_AUTH_PASSWORD}"